### ISSUE TITLE
error when using NetMHC

### ISSUE THREAD

**Issue by haoecust** [openvax/mhctools#119]
Hi, I came accorss an error on using netMHC through mhctools 1.6.5.

It works well with NetMHCpan and MHCflurry, with the fillowing commands
```
>>> from mhctools import NetMHCpan
>>> from mhctools import MHCflurry
>>> predictor1 = MHCflurry(alleles=["HLA-A0201"])
>>> predictor2 = NetMHCpan(alleles=["HLA-A0201"])
```

However, an error was reported, when I used NetMHC.  Since NetMHC-4.0 was well installed in the my local server and added into systhem path , when It works well with the command "netMHC" in linux command.   Did anyone came accross wthe same issue with me?
```
>>> from mhctools import NetMHC
>>> predictor = NetMHC(alleles=["HLA-A0201"])
```

` Unable to open(r) file /home/yeh/program/netMHC-4.0/Linux_x86_64/data/version
ERROR:mhctools.base_commandline_predictor:Unable to determine supported alleles
Traceback (most recent call last):
  File "mhctools/base_commandline_predictor.py", line 215, in _determine_supported_alleles
    raise ValueError("Unable to determine supported alleles")
ValueError: Unable to determine supported alleles
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mhctools/netmhc.py", line 59, in NetMHC
    program_name=program_name)
  File "mhctools/netmhc4.py", line 38, in __init__
    default_peptide_lengths=default_peptide_lengths)
  File "mhctools/base_commandline_predictor.py", line 159, in __init__
    self.supported_alleles_flag)
  File "mhctools/base_commandline_predictor.py", line 221, in _determine_supported_alleles
    supported_allele_flag))
SystemError: Failed to run netMHC -listMHC. Possibly an incorrect executable version?
`

Thanks 

Hao

**Comment by haoecust** [comment]
I guess I missed the file "http://www.cbs.dtu.dk/services/NetMHC-4.0/data.tar.gz".  Now, it works well.
