### ISSUE TITLE
Non-deterministic failure from CLI when using NetMHC 4.0

### ISSUE THREAD

**Issue by iskandr** [openvax/mhctools#121]
Running `$ mhctools --sequence HVKITDFGR --mhc-alleles A0203,B4403 --mhc-predictor netmhc` sometimes succeeds but sometimes fails with the following exception:
```
2017-10-03 18:49:14,241 - mhctools.process_helpers - INFO - Ran 2 commands in 0.0964 seconds
Traceback (most recent call last):
  File "/usr/local/bin/mhctools", line 11, in <module>
    load_entry_point('mhctools', 'console_scripts', 'mhctools')()
  File "/Users/iskander/code/mhctools/mhctools/cli/script.py", line 108, in main
    binding_predictions = run_predictor(args)
  File "/Users/iskander/code/mhctools/mhctools/cli/script.py", line 79, in run_predictor
    binding_predictions = predictor.predict_peptides(args.sequence)
  File "/Users/iskander/code/mhctools/mhctools/base_commandline_predictor.py", line 330, in predict_peptides
    alleles=self.alleles)
  File "/Users/iskander/code/mhctools/mhctools/base_predictor.py", line 143, in _check_results
    len(missing), example_peptide, example_allele))
ValueError: Missing 1 binding predictions, example peptide='HVKITDFGR' allele='HLA-A*02:03'
```

**Comment by iskandr** [comment]
Wonderful, NetMHC4 has negative positions in its output.

**Comment by iskandr** [comment]
Fixed by https://github.com/openvax/mhctools/pull/122
