### ISSUE TITLE
Make netmhc-3.4 go through Docker (like netChop)

### ISSUE THREAD

**Issue by julia326** [openvax/mhctools#134]
Has unpredictable behavior on at least one Mac, seeing a stack trace like:

```
(mhctools) admins-Air-3:mhctools julia$ mhctools --sequence AAAAAAAAAA --mhc-alleles A6801 --mhc-predictor netmhccons
2018-06-18 16:53:41,419 - mhctools.cli.args - INFO - Building MHC binding prediction type for alleles ['HLA-A*68:01'] and epitope lengths None
2018-06-18 16:53:41,566 - mhctools.process_helpers - INFO - netMHCcons took 0.1464 seconds
Traceback (most recent call last):
  File "/Users/julia/code/netmhc-bundle/netMHC-3.4/netMHC.py", line 536, in <module>
    main()
  File "/Users/julia/code/netmhc-bundle/netMHC-3.4/netMHC.py", line 523, in main
    preds[entry] = predfile2predlist(predfilename, NNpred, peplen, approxpred, ave)
  File "/Users/julia/code/netmhc-bundle/netMHC-3.4/netMHC.py", line 293, in predfile2predlist
    s = (s + float(myfields[3]))/2.0
IndexError: list index out of range
2018-06-18 16:53:43,096 - mhctools.process_helpers - INFO - Ran 1 commands in 1.5238 seconds
2018-06-18 16:53:43,099 - mhctools.base_commandline_predictor - WARNING - No binding predictions from netMHCcons
Traceback (most recent call last):
  File "/Users/julia/Envs/mhctools/bin/mhctools", line 11, in <module>
    load_entry_point('mhctools', 'console_scripts', 'mhctools')()
  File "/Users/julia/code/mhctools/mhctools/cli/script.py", line 115, in main
    binding_predictions = run_predictor(args)
  File "/Users/julia/code/mhctools/mhctools/cli/script.py", line 86, in run_predictor
    binding_predictions = predictor.predict_peptides(args.sequence)
  File "/Users/julia/code/mhctools/mhctools/base_commandline_predictor.py", line 330, in predict_peptides
    alleles=self.alleles)
  File "/Users/julia/code/mhctools/mhctools/base_predictor.py", line 143, in _check_results
    len(missing), example_peptide, example_allele))
ValueError: Missing 1 binding predictions, example peptide='AAAAAAAAAA' allele='HLA-A*68:01'
```

**Comment by iskandr** [comment]
No longer relevant — netMHC 3.4 is obsolete, the repo now supports NetMHC 4.0+ and NetMHCpan 4.x. No Docker infrastructure needed.
