### ISSUE TITLE
Test script doesn't work

### ISSUE THREAD

**Issue by julia326** [openvax/mhctools#66]
Running usage example:

```
mhctools
            --sequence SFFPIQQQQQAAALLLI \
            --sequence SILQQQAQAQQAQAASSSC \
            --mhc-predictor netmhc \
            --mhc-alleles HLA-A0201 H2-Db \
            --output-csv epitope.csv
```

Results in:

```
Traceback (most recent call last):
  File "/Users/julia/Envs/vaxrank-stack/bin/mhctools", line 11, in <module>
    load_entry_point('mhctools', 'console_scripts', 'mhctools')()
  File "/Users/julia/code/mhctools/mhctools/cli/script.py", line 64, in main
    df = epitope_collection.to_dataframe()
  File "/Users/julia/Envs/vaxrank-stack/lib/python2.7/site-packages/sercol/collection.py", line 66, in to_dataframe
    return pd.DataFrame.from_records([x.to_dict() for x in self])
AttributeError: 'BindingPrediction' object has no attribute 'to_dict'
```

**Comment by iskandr** [comment]
Old version of the `serializable` library? 

On my machine line 66 is this: 

```
        return pd.DataFrame.from_records([serializable.to_dict(x) for x in self])
```

(which does work without any fix)

**Comment by arahuja** [comment]
@iskandr I don't think that is checked in then: https://github.com/hammerlab/sercol/blob/master/sercol/collection.py#L66

**Comment by iskandr** [comment]
@arahuja You're right! Fixed here: https://github.com/hammerlab/sercol/pull/1
