### ISSUE TITLE
NetChop test fails

### ISSUE THREAD

**Issue by iskandr** [openvax/mhctools#84]
I just pulled from master and got this failure: 

```
======================================================================
FAIL: test.test_netchop.test_simple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iskander/Library/Python/2.7/lib/python/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/iskander/code/mhctools/test/test_netchop.py", line 15, in test_simple
    result = obj.predict(peptides)
  File "/Users/iskander/code/mhctools/mhctools/netchop.py", line 40, in predict
    assert len(parsed) == len(sequences)
AssertionError
```

**Comment by iskandr** [comment]
Saw a clue for why this failed:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```
